### ISSUE TITLE
Not working on my side

### ISSUE THREAD

**Issue by nkhs** [drmpeg/gr-dvbs2rx#1]
I cannot see Result file(decoded.ts)

This is my error logs
""""""""""""
Baseband header crc failed.
frame = 202, BCH decoder too many bit errors.
frame = 203, BCH decoder too many bit errors.
Baseband header crc failed.
frame = 204, BCH decoder too many bit errors.
frame = 205, BCH decoder too many bit errors.
Baseband header crc failed.
frame = 206, BCH decoder too many bit errors.
frame = 207, BCH decoder too many bit errors.
""""""""""""

**Comment by drmpeg** [comment]
Looks like there might be a regression with the DVB-T2 example. The DVB-S2 example (dvbs2_rx.grc) should still work okay.

**Comment by drmpeg** [comment]
I've updated the algorithm to use the corrected SNR instead of the hard decision estimate. This mostly solves the issue, but the current decoder still can't handle the old DVB-T2 example. That's because since the DVB-T2 example was introduced, the LDPC algorithm has been changed to sacrifice some error correcting performance in favor of vastly improved processing speed. I've changed the DVB-T2 example to use more reasonable parameters.
